services:
  php7_4:
    container_name: php7-4
    hostname: php7-4
    image: php:7.4-fpm-alpine3.13
    volumes:
      - ./php7_4:/var/www/html:rw

  postgres12:
    container_name: postgres12
    hostname: postgres12
    image: postgres:12-alpine
    environment:
      POSTGRES_PASSWORD: 12345
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - postgres12:/var/lib/postgresql/data:rw
      - ./postgres12/:/vol:rw
      - ./postgres12/postgresql.conf:/var/lib/postgresql/data/postgresql.conf:rw

  python3_9_6:
    container_name: python3_9_6
    hostname: python3_9_6
    image: python:3.9.6-alpine3.14
    ports:
      - "127.0.0.1:8080:8080"
    volumes:
      - ./python3_9_6/:/vol:rw


  prometheus2_32_0:
    container_name: prometheus2_32_0
    hostname: prometheus2_32_0
    image: prom/prometheus:v2.32.0
    ports:
      - "127.0.0.1:9090:9090"
    volumes:
      - prometheus2_32_0:/prometheus
      - ./prometheus:/config:rw
    command:
      - "--config.file=/config/prometheus.yaml"

  grafana8_3_3:
    container_name: grafana8_3_3
    hostname: grafana8_3_3
    image: grafana/grafana-oss:8.3.3
    ports:
      - "127.0.0.1:3000:3000"
    volumes:
      - grafana8_3_3:/var/lib/grafana:rw

volumes:
  postgres12:
  prometheus2_32_0:
  grafana8_3_3:
