DROP TABLE IF EXISTS T1;
CREATE TABLE T1 (label CHAR(1) PRIMARY KEY);

DROP TABLE IF EXISTS T2;
CREATE TABLE T2 (score INT PRIMARY KEY);

INSERT INTO T1 (label) VALUES('A');
INSERT INTO T1 (label) VALUES('B');

INSERT INTO T2 (score) VALUES(1);
INSERT INTO T2 (score) VALUES(2);
INSERT INTO T2 (score) VALUES(3);
