services:
  wordpress:
    container_name: wordpress5_8_2
    hostname: wordpress5_8_2
    image: wordpress:5.8.2-php8.1-fpm-alpine
    ports:
      - "127.0.0.1:8080:80"
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD: examplepass
      WORDPRESS_DB_NAME: exampledb
    network:
      - mysql8_0_26_wordpress5_8_2
    volumes:
      - ./www/:/var/www/html:rw

  db:
    container_name: mysql8_0_26
    hostname: mysql8_0_26
    image: mysql:8.0.26
    environment:
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    network:
      - mysql8_0_26_wordpress5_8_2
    volumes:
      - mysql8_0_26:/var/lib/mysql:rw

volumes:
  mysql8_0_26:

networks:
  mysql8_0_26_wordpress5_8_2:
